image: node:12

pages:
  script:
    - yarn install
    - sed -i "s/\/\/base/base/g" nuxt.config.js
    # - sed -i "s/\/\/publicPath/publicPath/g" nuxt.config.js
    - sed -i "s/PATHPREFIXTOREPLACE/$pathPrefix/g" nuxt.config.js
    - yarn generate
    # - mv public$publicPrefix/_nuxt public/
    - echo deploying to $CI_PAGES_URL
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master

pages-test:
  script:
    - yarn install
    - yarn generate
    - sed -i "s/\/\/base/base/g" nuxt.config.js
    # - sed -i "s/\/\/publicPath/publicPath/g" nuxt.config.js
    - sed -i "s/PATHPREFIXTOREPLACE/$pathPrefix/g" nuxt.config.js
    - cat nuxt.config.js
    - yarn generate
    # - echo mv public$publicPrefix/_nuxt public/
    # - mv public$publicPrefix/_nuxt public/
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - public
  only:
    - merge_requests
