name: Pull_Request
on:
  pull_request:
    branches:
      - master

env:
  pathPrefix: ${{ secrets.PATHPREFIX }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          ls
          npm install
          export pathPrefix=${{ env.pathPrefix }}
          sed -i "s/\/\/base/base/g" ./nuxt.config.js
          sed -i "s/PATHPREFIXTOREPLACE/$pathPrefix/g" ./nuxt.config.js
          cat nuxt.config.js
          npm run generate

      - uses: actions/upload-artifact@v1
        with:
          name: site
          path: public
